volumes:
  db_storage:
  n8n_storage:
  guiareal_db:
  redisinsight_data:

services:
  redis:
    image: redis:7-alpine
    container_name: guiareal_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: guiareal_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  guiareal_db:
    image: postgres:16
    container_name: guiareal_db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=guiareal
      - POSTGRES_PASSWORD=guiareal
      - POSTGRES_DB=guiareal
    volumes:
      - guiareal_db:/var/lib/postgresql/data

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
